export const students = [
  {
    name: "John Doe",
    id: "142",
    gender: "Male",
    age: 18,
    grade: "12th",
    motherName: "Jane Doe",
    motherEmail: "jane.doe@example.com",
    motherPhoneNumber: "1234567890",
    fatherName: "John Doe Sr.",
    fatherEmail: "john.doe@example.com",
    fatherPhoneNumber: "9876543210",
    address: "123 Main Street"
  },
  {
    name: "Jane Smith",
    id: "143",
    gender: "Female",
    age: 17,
    grade: "11th",
    motherName: "Mary Smith",
    motherEmail: "mary.smith@example.com",
    motherPhoneNumber: "1112223333",
    fatherName: "Robert Smith",
    fatherEmail: "robert.smith@example.com",
    fatherPhoneNumber: "4445556666",
    address: "456 Oak Avenue"
  },
  {
    name: "Alex Johnson",
    id: "144",
    gender: "Male",
    age: 16,
    grade: "10th",
    motherName: "Emily Johnson",
    motherEmail: "emily.johnson@example.com",
    motherPhoneNumber: "9998887777",
    fatherName: "Michael Johnson",
    fatherEmail: "michael.johnson@example.com",
    fatherPhoneNumber: "6667778888",
    address: "789 Elm Street"
  },
  {
    name: "Emily Wilson",
    id: "145",
    gender: "Female",
    age: 16,
    grade: "10th",
    motherName: "Olivia Wilson",
    motherEmail: "olivia.wilson@example.com",
    motherPhoneNumber: "2223334444",
    fatherName: "William Wilson",
    fatherEmail: "william.wilson@example.com",
    fatherPhoneNumber: "7778889999",
    address: "321 Maple Avenue"
  },
  {
    name: "David Brown",
    id: "146",
    gender: "Male",
    age: 15,
    grade: "9th",
    motherName: "Jessica Brown",
    motherEmail: "jessica.brown@example.com",
    motherPhoneNumber: "5556667777",
    fatherName: "Christopher Brown",
    fatherEmail: "christopher.brown@example.com",
    fatherPhoneNumber: "2223334444",
    address: "987 Oak Street"
  },
  {
    name: "Sarah Davis",
    id: "147",
    gender: "Female",
    age: 17,
    grade: "11th",
    motherName: "Amanda Davis",
    motherEmail: "amanda.davis@example.com",
    motherPhoneNumber: "7776665555",
    fatherName: "Matthew Davis",
    fatherEmail: "matthew.davis@example.com",
    fatherPhoneNumber: "4445556666",
    address: "654 Pine Avenue"
  },
  {
    name: "Michael Lee",
    id: "148",
    gender: "Male",
    age: 16,
    grade: "10th",
    motherName: "Sophia Lee",
    motherEmail: "sophia.lee@example.com",
    motherPhoneNumber: "6665554444",
    fatherName: "Daniel Lee",
    fatherEmail: "daniel.lee@example.com",
    fatherPhoneNumber: "3334445555",
    address: "852 Cedar Street"
  },
  {
    name: "Jessica Taylor",
    id: "149",
    gender: "Female",
    age: 15,
    grade: "9th",
    motherName: "Isabella Taylor",
    motherEmail: "isabella.taylor@example.com",
    motherPhoneNumber: "4443332222",
    fatherName: "Andrew Taylor",
    fatherEmail: "andrew.taylor@example.com",
    fatherPhoneNumber: "1112223333",
    address: "369 Elm Avenue"
  },
  {
    name: "Christopher Clark",
    id: "150",
    gender: "Male",
    age: 17,
    grade: "11th",
    motherName: "Sophie Clark",
    motherEmail: "sophie.clark@example.com",
    motherPhoneNumber: "7778889999",
    fatherName: "Benjamin Clark",
    fatherEmail: "benjamin.clark@example.com",
    fatherPhoneNumber: "4445556666",
    address: "753 Pine Street"
  },
  {
    name: "Amanda Hall",
    id: "151",
    gender: "Female",
    age: 15,
    grade: "9th",
    motherName: "Chloe Hall",
    motherEmail: "chloe.hall@example.com",
    motherPhoneNumber: "9998887777",
    fatherName: "Joseph Hall",
    fatherEmail: "joseph.hall@example.com",
    fatherPhoneNumber: "6667778888",
    address: "963 Oak Avenue"
  },
];